version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: dennisoooo/edu-frontend:v1
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000  # 修改這裡，使用服務名稱
    depends_on:
      - backend


  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: dennisoooo/edu-backend:v1
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
    command: python manage.py runserver 0.0.0.0:8000


